package com.wondersgroup.tzscws1.dao;

import com.wondersgroup.tzscws1.model.CodeInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;

@Mapper
@Component(value = "codeInfoMapper")
public interface CodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    int insert(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    int insertSelective(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    CodeInfo selectByPrimaryKey(BigDecimal id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    List<CodeInfo> selectByCodeInfoId(BigDecimal id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeInfo record);
}