package com.wondersgroup.tzscws1.dao;

import com.wondersgroup.tzscws1.model.ZybGak;
import org.apache.ibatis.annotations.Mapper;

import java.util.HashMap;

@Mapper
public interface ZybGakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int insert(ZybGak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int insertSelective(ZybGak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    ZybGak selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZybGak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZybGak record);

    ZybGak selectByCodeAndHosId(HashMap map);
}