package com.wondersgroup.tzscws1.dao;

import com.wondersgroup.tzscws1.model.ZybGak;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Mapper
public interface ZybGakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int insert(ZybGak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int insertSelective(ZybGak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    ZybGak selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZybGak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_GAK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZybGak record);

    ZybGak selectByCodeAndHosId(HashMap map);

    /**
     * 调用上传省平台接口查找数据
     * @return
     */
    List<ZybGak> selectForCallProvincial(@Param("params") Map<String, Object> params);

    /**
     * 根据参数查找数据
     * @return
     */
    List<ZybGak> selectByParams(@Param("params") Map<String, Object> params);

    /**
     * 批量插入
     * @param zybGakList
     * @return
     */
    boolean insertBatch(List<ZybGak> zybGakList);
}
