package com.wondersgroup.tzscws1.dao;

import com.wondersgroup.tzscws1.model.ZybYrdw;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;


@Mapper
public interface ZybYrdwMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_YRDW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String employerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_YRDW
     *
     * @mbggenerated
     */
    int insert(ZybYrdw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_YRDW
     *
     * @mbggenerated
     */
    int insertSelective(ZybYrdw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_YRDW
     *
     * @mbggenerated
     */
    ZybYrdw selectByPrimaryKey(String employerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_YRDW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZybYrdw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZYB_YRDW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZybYrdw record);

    List<ZybYrdw> selectByEmployerName(String employerName);

    /**
     * 根据id批量查找
     * @param idList id列表
     * @return
     */
    List<ZybYrdw> selectByIdList(@Param("idList") List<String> idList);
}