# 长沙开发数据库
server:
  port: 8080

spring:
  datasource:
    username: jbyfkzuser
    password: jbyfkzuser
    url: jdbc:oracle:thin:@10.1.94.84:1521/jbyfkzdb
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wondersgroup.tzscws1.model


#showSql
logging:
  level:
    com:
      example:
          mapper : debug

callProvincialPlatformTime: 10000

# 调用省平台上传接口需要的参数
provincialPlatform:
  url: https://www.xiaoyisheng.net.cn/ws_data/ws/TJ?wsdl
  method: transport
  # 请求参数头中的hosid
  headerHosId: 33100000