server:
  port: 8080

spring:
  datasource:
    username: tzjk_uat
    password: tzjk_uat
    #url: jdbc:oracle:thin:@20.76.200.103:1521/orcl
    url: jdbc:oracle:thin:@172.16.8.251:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wondersgroup.tzscws1.model


#showSql
logging:
  level:
    com:
      example:
          mapper : debug

callProvincialPlatformTime: 3600000

# 调用省平台上传接口时，请求参数头中的hosid
headerHosId: 33100000