package com.wondersgroup.tzscws1.model;

import java.math.BigDecimal;

public class CodeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.CODE_INFO_ID
     *
     * @mbggenerated
     */
    private BigDecimal codeInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.DISP_ORDER
     *
     * @mbggenerated
     */
    private Long dispOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.REMARK1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.REMARK2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.OPERATE_TIME
     *
     * @mbggenerated
     */
    private BigDecimal operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.REMOVED
     *
     * @mbggenerated
     */
    private Long removed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.ID
     *
     * @return the value of CODE_INFO.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.ID
     *
     * @param id the value for CODE_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.CODE_INFO_ID
     *
     * @return the value of CODE_INFO.CODE_INFO_ID
     *
     * @mbggenerated
     */
    public BigDecimal getCodeInfoId() {
        return codeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.CODE_INFO_ID
     *
     * @param codeInfoId the value for CODE_INFO.CODE_INFO_ID
     *
     * @mbggenerated
     */
    public void setCodeInfoId(BigDecimal codeInfoId) {
        this.codeInfoId = codeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.TYPE_ID
     *
     * @return the value of CODE_INFO.TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.TYPE_ID
     *
     * @param typeId the value for CODE_INFO.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(BigDecimal typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.DISP_ORDER
     *
     * @return the value of CODE_INFO.DISP_ORDER
     *
     * @mbggenerated
     */
    public Long getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.DISP_ORDER
     *
     * @param dispOrder the value for CODE_INFO.DISP_ORDER
     *
     * @mbggenerated
     */
    public void setDispOrder(Long dispOrder) {
        this.dispOrder = dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.REMARK1
     *
     * @return the value of CODE_INFO.REMARK1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.REMARK1
     *
     * @param remark1 the value for CODE_INFO.REMARK1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.REMARK2
     *
     * @return the value of CODE_INFO.REMARK2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.REMARK2
     *
     * @param remark2 the value for CODE_INFO.REMARK2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.OPERATE_TIME
     *
     * @return the value of CODE_INFO.OPERATE_TIME
     *
     * @mbggenerated
     */
    public BigDecimal getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.OPERATE_TIME
     *
     * @param operateTime the value for CODE_INFO.OPERATE_TIME
     *
     * @mbggenerated
     */
    public void setOperateTime(BigDecimal operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.OPERATOR
     *
     * @return the value of CODE_INFO.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.OPERATOR
     *
     * @param operator the value for CODE_INFO.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.REMOVED
     *
     * @return the value of CODE_INFO.REMOVED
     *
     * @mbggenerated
     */
    public Long getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.REMOVED
     *
     * @param removed the value for CODE_INFO.REMOVED
     *
     * @mbggenerated
     */
    public void setRemoved(Long removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.CODE
     *
     * @return the value of CODE_INFO.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.CODE
     *
     * @param code the value for CODE_INFO.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.NAME
     *
     * @return the value of CODE_INFO.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.NAME
     *
     * @param name the value for CODE_INFO.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_INFO.DESCRIPTION
     *
     * @return the value of CODE_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_INFO.DESCRIPTION
     *
     * @param description the value for CODE_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}