package com.wondersgroup.tzscws1.model;

import java.math.BigDecimal;
import java.util.Date;

public class ZybGak {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HOS_ID
     *
     * @mbggenerated
     */
    private String hosId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ORG_CODE
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.EMPLOYER_NAME
     *
     * @mbggenerated
     */
    private String employerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.IDCARD
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.TEL_PHONE
     *
     * @mbggenerated
     */
    private String telPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.BODY_CHECK_TYPE
     *
     * @mbggenerated
     */
    private Short bodyCheckType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ID
     *
     * @mbggenerated
     */
    private Date bodyCheckTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SEX_CODE
     *
     * @mbggenerated
     */
    private Short sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SENIORITY_YEAR
     *
     * @mbggenerated
     */
    private Short seniorityYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SENIORITY_MONTH
     *
     * @mbggenerated
     */
    private Short seniorityMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HAZARD_CODE
     *
     * @mbggenerated
     */
    private String hazardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.EXPOSURE_YEAR
     *
     * @mbggenerated
     */
    private Short exposureYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.EXPOSURE_MONTH
     *
     * @mbggenerated
     */
    private Short exposureMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HAZARD_YEAR
     *
     * @mbggenerated
     */
    private Short hazardYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HAZARD_MONTH
     *
     * @mbggenerated
     */
    private Short hazardMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.WORK_SHOP
     *
     * @mbggenerated
     */
    private String workShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.JOB_CODE
     *
     * @mbggenerated
     */
    private String jobCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SYS_PRESS_RESULT
     *
     * @mbggenerated
     */
    private BigDecimal sysPressResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SYS_PRESS_UNIT_NAME
     *
     * @mbggenerated
     */
    private String sysPressUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.DIAS_PRESS_RESULT
     *
     * @mbggenerated
     */
    private BigDecimal diasPressResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.DIAS_PRESS_UNIT_NAME
     *
     * @mbggenerated
     */
    private String diasPressUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.WBC_RESULT
     *
     * @mbggenerated
     */
    private String wbcResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.WBC_UNIT_NAME
     *
     * @mbggenerated
     */
    private String wbcUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.WBC_MINI_RANGE
     *
     * @mbggenerated
     */
    private String wbcMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.WBC_MAX_RANGE
     *
     * @mbggenerated
     */
    private String wbcMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.RBC_RESULT
     *
     * @mbggenerated
     */
    private String rbcResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.RBC_UNIT_NAME
     *
     * @mbggenerated
     */
    private String rbcUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.RBC_MINI_RANGE
     *
     * @mbggenerated
     */
    private String rbcMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.RBC_MAX_RANGE
     *
     * @mbggenerated
     */
    private String rbcMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HB_RESULT
     *
     * @mbggenerated
     */
    private String hbResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HB_UNIT_NAME
     *
     * @mbggenerated
     */
    private String hbUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HB_MINI_RANGE
     *
     * @mbggenerated
     */
    private String hbMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HB_MAX_RANGE
     *
     * @mbggenerated
     */
    private String hbMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PLT_RESULT
     *
     * @mbggenerated
     */
    private String pltResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PLT_UNIT_NAME
     *
     * @mbggenerated
     */
    private String pltUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PLT_MINI_RANGE
     *
     * @mbggenerated
     */
    private String pltMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PLT_MAX_RANGE
     *
     * @mbggenerated
     */
    private String pltMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.GLU_RESULT
     *
     * @mbggenerated
     */
    private String gluResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.GLU_UNIT_NAME
     *
     * @mbggenerated
     */
    private String gluUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.GLU_MINI_RANGE
     *
     * @mbggenerated
     */
    private String gluMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.GLU_MAX_RANGE
     *
     * @mbggenerated
     */
    private String gluMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PRO_RESULT
     *
     * @mbggenerated
     */
    private String proResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PRO_UNIT_NAME
     *
     * @mbggenerated
     */
    private String proUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PRO_MINI_RANGE
     *
     * @mbggenerated
     */
    private String proMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.PRO_MAX_RANGE
     *
     * @mbggenerated
     */
    private String proMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.UWBC_RESULT
     *
     * @mbggenerated
     */
    private String uwbcResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.UWBC_UNIT_NAME
     *
     * @mbggenerated
     */
    private String uwbcUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.UWBC_MINI_RANGE
     *
     * @mbggenerated
     */
    private String uwbcMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.UWBC_MAX_RANGE
     *
     * @mbggenerated
     */
    private String uwbcMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.BLD_RESULT
     *
     * @mbggenerated
     */
    private String bldResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.BLD_UNIT_NAME
     *
     * @mbggenerated
     */
    private String bldUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.BLD_MINI_RANGE
     *
     * @mbggenerated
     */
    private String bldMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.BLD_MAX_RANGE
     *
     * @mbggenerated
     */
    private String bldMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ALT_RESULT
     *
     * @mbggenerated
     */
    private String altResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ALT_UNIT_NAME
     *
     * @mbggenerated
     */
    private String altUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ALT_MINI_RANGE
     *
     * @mbggenerated
     */
    private String altMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ALT_MAX_RANGE
     *
     * @mbggenerated
     */
    private String altMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ECG_CODE
     *
     * @mbggenerated
     */
    private String ecgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.CHEST_CODE
     *
     * @mbggenerated
     */
    private String chestCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FVC_RESULT
     *
     * @mbggenerated
     */
    private String fvcResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FVC_UNIT_NAME
     *
     * @mbggenerated
     */
    private String fvcUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FVC_MINI_RANGE
     *
     * @mbggenerated
     */
    private String fvcMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FVC_MAX_RANGE
     *
     * @mbggenerated
     */
    private String fvcMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1_RESULT
     *
     * @mbggenerated
     */
    private String fev1Result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1_UNIT_NAME
     *
     * @mbggenerated
     */
    private String fev1UnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1_MINI_RANGE
     *
     * @mbggenerated
     */
    private String fev1MiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1_MAX_RANGE
     *
     * @mbggenerated
     */
    private String fev1MaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1FVC_RESULT
     *
     * @mbggenerated
     */
    private String fev1fvcResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1FVC_UNIT_NAME
     *
     * @mbggenerated
     */
    private String fev1fvcUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1FVC_MINI_RANGE
     *
     * @mbggenerated
     */
    private String fev1fvcMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.FEV1FVC_MAX_RANGE
     *
     * @mbggenerated
     */
    private String fev1fvcMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.B_LEAD_RESULT
     *
     * @mbggenerated
     */
    private String bLeadResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.B_LEAD_UNIT_NAME
     *
     * @mbggenerated
     */
    private String bLeadUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.B_LEAD_MINI_RANGE
     *
     * @mbggenerated
     */
    private String bLeadMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.B_LEAD_MAX_RANGE
     *
     * @mbggenerated
     */
    private String bLeadMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.U_LEAD_RESULT
     *
     * @mbggenerated
     */
    private String uLeadResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.U_LEAD_UNIT_NAME
     *
     * @mbggenerated
     */
    private String uLeadUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.U_LEAD_MINI_RANGE
     *
     * @mbggenerated
     */
    private String uLeadMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.U_LEAD_MAX_RANGE
     *
     * @mbggenerated
     */
    private String uLeadMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ZPP_RESULT
     *
     * @mbggenerated
     */
    private String zppResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ZPP_UNIT_NAME
     *
     * @mbggenerated
     */
    private String zppUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ZPP_MINI_RANGE
     *
     * @mbggenerated
     */
    private String zppMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.ZPP_MAX_RANGE
     *
     * @mbggenerated
     */
    private String zppMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.NEUT_RESULT
     *
     * @mbggenerated
     */
    private String neutResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.NEUT_UNIT_NAME
     *
     * @mbggenerated
     */
    private String neutUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.NEUT_MINI_RANGE
     *
     * @mbggenerated
     */
    private String neutMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.NEUT_MAX_RANGE
     *
     * @mbggenerated
     */
    private String neutMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HEARING_REUSLT
     *
     * @mbggenerated
     */
    private String hearingReuslt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HEARING_UNIT_NAME
     *
     * @mbggenerated
     */
    private String hearingUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HEARING_MINI_RANGE
     *
     * @mbggenerated
     */
    private String hearingMiniRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.HEARING_MAX_RANGE
     *
     * @mbggenerated
     */
    private String hearingMaxRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.RPBT_CODE
     *
     * @mbggenerated
     */
    private Short rpbtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.WRIGHT_CODE
     *
     * @mbggenerated
     */
    private BigDecimal wrightCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.CONCLUSIONS_CODE
     *
     * @mbggenerated
     */
    private Short conclusionsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SHBZ
     *
     * @mbggenerated
     */
    private String shbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SHSJ
     *
     * @mbggenerated
     */
    private Date shsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SBBZ
     *
     * @mbggenerated
     */
    private String sbbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SBYY
     *
     * @mbggenerated
     */
    private String sbyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.SBSJ
     *
     * @mbggenerated
     */
    private Date sbsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZYB_GAK.LOGSJ
     *
     * @mbggenerated
     */
    private Date logsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ID
     *
     * @return the value of ZYB_GAK.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ID
     *
     * @param id the value for ZYB_GAK.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.CODE
     *
     * @return the value of ZYB_GAK.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.CODE
     *
     * @param code the value for ZYB_GAK.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HOS_ID
     *
     * @return the value of ZYB_GAK.HOS_ID
     *
     * @mbggenerated
     */
    public String getHosId() {
        return hosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HOS_ID
     *
     * @param hosId the value for ZYB_GAK.HOS_ID
     *
     * @mbggenerated
     */
    public void setHosId(String hosId) {
        this.hosId = hosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ORG_CODE
     *
     * @return the value of ZYB_GAK.ORG_CODE
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ORG_CODE
     *
     * @param orgCode the value for ZYB_GAK.ORG_CODE
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.EMPLOYER_NAME
     *
     * @return the value of ZYB_GAK.EMPLOYER_NAME
     *
     * @mbggenerated
     */
    public String getEmployerName() {
        return employerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.EMPLOYER_NAME
     *
     * @param employerName the value for ZYB_GAK.EMPLOYER_NAME
     *
     * @mbggenerated
     */
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.NAME
     *
     * @return the value of ZYB_GAK.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.NAME
     *
     * @param name the value for ZYB_GAK.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.IDCARD
     *
     * @return the value of ZYB_GAK.IDCARD
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.IDCARD
     *
     * @param idcard the value for ZYB_GAK.IDCARD
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.TEL_PHONE
     *
     * @return the value of ZYB_GAK.TEL_PHONE
     *
     * @mbggenerated
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.TEL_PHONE
     *
     * @param telPhone the value for ZYB_GAK.TEL_PHONE
     *
     * @mbggenerated
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.BODY_CHECK_TYPE
     *
     * @return the value of ZYB_GAK.BODY_CHECK_TYPE
     *
     * @mbggenerated
     */
    public Short getBodyCheckType() {
        return bodyCheckType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.BODY_CHECK_TYPE
     *
     * @param bodyCheckType the value for ZYB_GAK.BODY_CHECK_TYPE
     *
     * @mbggenerated
     */
    public void setBodyCheckType(Short bodyCheckType) {
        this.bodyCheckType = bodyCheckType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SEX_CODE
     *
     * @return the value of ZYB_GAK.SEX_CODE
     *
     * @mbggenerated
     */
    public Short getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SEX_CODE
     *
     * @param sexCode the value for ZYB_GAK.SEX_CODE
     *
     * @mbggenerated
     */
    public void setSexCode(Short sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.BIRTHDAY
     *
     * @return the value of ZYB_GAK.BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.BIRTHDAY
     *
     * @param birthday the value for ZYB_GAK.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SENIORITY_YEAR
     *
     * @return the value of ZYB_GAK.SENIORITY_YEAR
     *
     * @mbggenerated
     */
    public Short getSeniorityYear() {
        return seniorityYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SENIORITY_YEAR
     *
     * @param seniorityYear the value for ZYB_GAK.SENIORITY_YEAR
     *
     * @mbggenerated
     */
    public void setSeniorityYear(Short seniorityYear) {
        this.seniorityYear = seniorityYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SENIORITY_MONTH
     *
     * @return the value of ZYB_GAK.SENIORITY_MONTH
     *
     * @mbggenerated
     */
    public Short getSeniorityMonth() {
        return seniorityMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SENIORITY_MONTH
     *
     * @param seniorityMonth the value for ZYB_GAK.SENIORITY_MONTH
     *
     * @mbggenerated
     */
    public void setSeniorityMonth(Short seniorityMonth) {
        this.seniorityMonth = seniorityMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HAZARD_CODE
     *
     * @return the value of ZYB_GAK.HAZARD_CODE
     *
     * @mbggenerated
     */
    public String getHazardCode() {
        return hazardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HAZARD_CODE
     *
     * @param hazardCode the value for ZYB_GAK.HAZARD_CODE
     *
     * @mbggenerated
     */
    public void setHazardCode(String hazardCode) {
        this.hazardCode = hazardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.EXPOSURE_YEAR
     *
     * @return the value of ZYB_GAK.EXPOSURE_YEAR
     *
     * @mbggenerated
     */
    public Short getExposureYear() {
        return exposureYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.EXPOSURE_YEAR
     *
     * @param exposureYear the value for ZYB_GAK.EXPOSURE_YEAR
     *
     * @mbggenerated
     */
    public void setExposureYear(Short exposureYear) {
        this.exposureYear = exposureYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.EXPOSURE_MONTH
     *
     * @return the value of ZYB_GAK.EXPOSURE_MONTH
     *
     * @mbggenerated
     */
    public Short getExposureMonth() {
        return exposureMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.EXPOSURE_MONTH
     *
     * @param exposureMonth the value for ZYB_GAK.EXPOSURE_MONTH
     *
     * @mbggenerated
     */
    public void setExposureMonth(Short exposureMonth) {
        this.exposureMonth = exposureMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HAZARD_YEAR
     *
     * @return the value of ZYB_GAK.HAZARD_YEAR
     *
     * @mbggenerated
     */
    public Short getHazardYear() {
        return hazardYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HAZARD_YEAR
     *
     * @param hazardYear the value for ZYB_GAK.HAZARD_YEAR
     *
     * @mbggenerated
     */
    public void setHazardYear(Short hazardYear) {
        this.hazardYear = hazardYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HAZARD_MONTH
     *
     * @return the value of ZYB_GAK.HAZARD_MONTH
     *
     * @mbggenerated
     */
    public Short getHazardMonth() {
        return hazardMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HAZARD_MONTH
     *
     * @param hazardMonth the value for ZYB_GAK.HAZARD_MONTH
     *
     * @mbggenerated
     */
    public void setHazardMonth(Short hazardMonth) {
        this.hazardMonth = hazardMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.WORK_SHOP
     *
     * @return the value of ZYB_GAK.WORK_SHOP
     *
     * @mbggenerated
     */
    public String getWorkShop() {
        return workShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.WORK_SHOP
     *
     * @param workShop the value for ZYB_GAK.WORK_SHOP
     *
     * @mbggenerated
     */
    public void setWorkShop(String workShop) {
        this.workShop = workShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.JOB_CODE
     *
     * @return the value of ZYB_GAK.JOB_CODE
     *
     * @mbggenerated
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.JOB_CODE
     *
     * @param jobCode the value for ZYB_GAK.JOB_CODE
     *
     * @mbggenerated
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SYS_PRESS_RESULT
     *
     * @return the value of ZYB_GAK.SYS_PRESS_RESULT
     *
     * @mbggenerated
     */
    public BigDecimal getSysPressResult() {
        return sysPressResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SYS_PRESS_RESULT
     *
     * @param sysPressResult the value for ZYB_GAK.SYS_PRESS_RESULT
     *
     * @mbggenerated
     */
    public void setSysPressResult(BigDecimal sysPressResult) {
        this.sysPressResult = sysPressResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SYS_PRESS_UNIT_NAME
     *
     * @return the value of ZYB_GAK.SYS_PRESS_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getSysPressUnitName() {
        return sysPressUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SYS_PRESS_UNIT_NAME
     *
     * @param sysPressUnitName the value for ZYB_GAK.SYS_PRESS_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setSysPressUnitName(String sysPressUnitName) {
        this.sysPressUnitName = sysPressUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.DIAS_PRESS_RESULT
     *
     * @return the value of ZYB_GAK.DIAS_PRESS_RESULT
     *
     * @mbggenerated
     */
    public BigDecimal getDiasPressResult() {
        return diasPressResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.DIAS_PRESS_RESULT
     *
     * @param diasPressResult the value for ZYB_GAK.DIAS_PRESS_RESULT
     *
     * @mbggenerated
     */
    public void setDiasPressResult(BigDecimal diasPressResult) {
        this.diasPressResult = diasPressResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.DIAS_PRESS_UNIT_NAME
     *
     * @return the value of ZYB_GAK.DIAS_PRESS_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getDiasPressUnitName() {
        return diasPressUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.DIAS_PRESS_UNIT_NAME
     *
     * @param diasPressUnitName the value for ZYB_GAK.DIAS_PRESS_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setDiasPressUnitName(String diasPressUnitName) {
        this.diasPressUnitName = diasPressUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.WBC_RESULT
     *
     * @return the value of ZYB_GAK.WBC_RESULT
     *
     * @mbggenerated
     */
    public String getWbcResult() {
        return wbcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.WBC_RESULT
     *
     * @param wbcResult the value for ZYB_GAK.WBC_RESULT
     *
     * @mbggenerated
     */
    public void setWbcResult(String wbcResult) {
        this.wbcResult = wbcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.WBC_UNIT_NAME
     *
     * @return the value of ZYB_GAK.WBC_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getWbcUnitName() {
        return wbcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.WBC_UNIT_NAME
     *
     * @param wbcUnitName the value for ZYB_GAK.WBC_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setWbcUnitName(String wbcUnitName) {
        this.wbcUnitName = wbcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.WBC_MINI_RANGE
     *
     * @return the value of ZYB_GAK.WBC_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getWbcMiniRange() {
        return wbcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.WBC_MINI_RANGE
     *
     * @param wbcMiniRange the value for ZYB_GAK.WBC_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setWbcMiniRange(String wbcMiniRange) {
        this.wbcMiniRange = wbcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.WBC_MAX_RANGE
     *
     * @return the value of ZYB_GAK.WBC_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getWbcMaxRange() {
        return wbcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.WBC_MAX_RANGE
     *
     * @param wbcMaxRange the value for ZYB_GAK.WBC_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setWbcMaxRange(String wbcMaxRange) {
        this.wbcMaxRange = wbcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.RBC_RESULT
     *
     * @return the value of ZYB_GAK.RBC_RESULT
     *
     * @mbggenerated
     */
    public String getRbcResult() {
        return rbcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.RBC_RESULT
     *
     * @param rbcResult the value for ZYB_GAK.RBC_RESULT
     *
     * @mbggenerated
     */
    public void setRbcResult(String rbcResult) {
        this.rbcResult = rbcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.RBC_UNIT_NAME
     *
     * @return the value of ZYB_GAK.RBC_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getRbcUnitName() {
        return rbcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.RBC_UNIT_NAME
     *
     * @param rbcUnitName the value for ZYB_GAK.RBC_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setRbcUnitName(String rbcUnitName) {
        this.rbcUnitName = rbcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.RBC_MINI_RANGE
     *
     * @return the value of ZYB_GAK.RBC_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getRbcMiniRange() {
        return rbcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.RBC_MINI_RANGE
     *
     * @param rbcMiniRange the value for ZYB_GAK.RBC_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setRbcMiniRange(String rbcMiniRange) {
        this.rbcMiniRange = rbcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.RBC_MAX_RANGE
     *
     * @return the value of ZYB_GAK.RBC_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getRbcMaxRange() {
        return rbcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.RBC_MAX_RANGE
     *
     * @param rbcMaxRange the value for ZYB_GAK.RBC_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setRbcMaxRange(String rbcMaxRange) {
        this.rbcMaxRange = rbcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HB_RESULT
     *
     * @return the value of ZYB_GAK.HB_RESULT
     *
     * @mbggenerated
     */
    public String getHbResult() {
        return hbResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HB_RESULT
     *
     * @param hbResult the value for ZYB_GAK.HB_RESULT
     *
     * @mbggenerated
     */
    public void setHbResult(String hbResult) {
        this.hbResult = hbResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HB_UNIT_NAME
     *
     * @return the value of ZYB_GAK.HB_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getHbUnitName() {
        return hbUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HB_UNIT_NAME
     *
     * @param hbUnitName the value for ZYB_GAK.HB_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setHbUnitName(String hbUnitName) {
        this.hbUnitName = hbUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HB_MINI_RANGE
     *
     * @return the value of ZYB_GAK.HB_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getHbMiniRange() {
        return hbMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HB_MINI_RANGE
     *
     * @param hbMiniRange the value for ZYB_GAK.HB_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setHbMiniRange(String hbMiniRange) {
        this.hbMiniRange = hbMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HB_MAX_RANGE
     *
     * @return the value of ZYB_GAK.HB_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getHbMaxRange() {
        return hbMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HB_MAX_RANGE
     *
     * @param hbMaxRange the value for ZYB_GAK.HB_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setHbMaxRange(String hbMaxRange) {
        this.hbMaxRange = hbMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PLT_RESULT
     *
     * @return the value of ZYB_GAK.PLT_RESULT
     *
     * @mbggenerated
     */
    public String getPltResult() {
        return pltResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PLT_RESULT
     *
     * @param pltResult the value for ZYB_GAK.PLT_RESULT
     *
     * @mbggenerated
     */
    public void setPltResult(String pltResult) {
        this.pltResult = pltResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PLT_UNIT_NAME
     *
     * @return the value of ZYB_GAK.PLT_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getPltUnitName() {
        return pltUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PLT_UNIT_NAME
     *
     * @param pltUnitName the value for ZYB_GAK.PLT_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setPltUnitName(String pltUnitName) {
        this.pltUnitName = pltUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PLT_MINI_RANGE
     *
     * @return the value of ZYB_GAK.PLT_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getPltMiniRange() {
        return pltMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PLT_MINI_RANGE
     *
     * @param pltMiniRange the value for ZYB_GAK.PLT_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setPltMiniRange(String pltMiniRange) {
        this.pltMiniRange = pltMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PLT_MAX_RANGE
     *
     * @return the value of ZYB_GAK.PLT_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getPltMaxRange() {
        return pltMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PLT_MAX_RANGE
     *
     * @param pltMaxRange the value for ZYB_GAK.PLT_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setPltMaxRange(String pltMaxRange) {
        this.pltMaxRange = pltMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.GLU_RESULT
     *
     * @return the value of ZYB_GAK.GLU_RESULT
     *
     * @mbggenerated
     */
    public String getGluResult() {
        return gluResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.GLU_RESULT
     *
     * @param gluResult the value for ZYB_GAK.GLU_RESULT
     *
     * @mbggenerated
     */
    public void setGluResult(String gluResult) {
        this.gluResult = gluResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.GLU_UNIT_NAME
     *
     * @return the value of ZYB_GAK.GLU_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getGluUnitName() {
        return gluUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.GLU_UNIT_NAME
     *
     * @param gluUnitName the value for ZYB_GAK.GLU_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setGluUnitName(String gluUnitName) {
        this.gluUnitName = gluUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.GLU_MINI_RANGE
     *
     * @return the value of ZYB_GAK.GLU_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getGluMiniRange() {
        return gluMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.GLU_MINI_RANGE
     *
     * @param gluMiniRange the value for ZYB_GAK.GLU_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setGluMiniRange(String gluMiniRange) {
        this.gluMiniRange = gluMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.GLU_MAX_RANGE
     *
     * @return the value of ZYB_GAK.GLU_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getGluMaxRange() {
        return gluMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.GLU_MAX_RANGE
     *
     * @param gluMaxRange the value for ZYB_GAK.GLU_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setGluMaxRange(String gluMaxRange) {
        this.gluMaxRange = gluMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PRO_RESULT
     *
     * @return the value of ZYB_GAK.PRO_RESULT
     *
     * @mbggenerated
     */
    public String getProResult() {
        return proResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PRO_RESULT
     *
     * @param proResult the value for ZYB_GAK.PRO_RESULT
     *
     * @mbggenerated
     */
    public void setProResult(String proResult) {
        this.proResult = proResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PRO_UNIT_NAME
     *
     * @return the value of ZYB_GAK.PRO_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getProUnitName() {
        return proUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PRO_UNIT_NAME
     *
     * @param proUnitName the value for ZYB_GAK.PRO_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setProUnitName(String proUnitName) {
        this.proUnitName = proUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PRO_MINI_RANGE
     *
     * @return the value of ZYB_GAK.PRO_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getProMiniRange() {
        return proMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PRO_MINI_RANGE
     *
     * @param proMiniRange the value for ZYB_GAK.PRO_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setProMiniRange(String proMiniRange) {
        this.proMiniRange = proMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.PRO_MAX_RANGE
     *
     * @return the value of ZYB_GAK.PRO_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getProMaxRange() {
        return proMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.PRO_MAX_RANGE
     *
     * @param proMaxRange the value for ZYB_GAK.PRO_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setProMaxRange(String proMaxRange) {
        this.proMaxRange = proMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.UWBC_RESULT
     *
     * @return the value of ZYB_GAK.UWBC_RESULT
     *
     * @mbggenerated
     */
    public String getUwbcResult() {
        return uwbcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.UWBC_RESULT
     *
     * @param uwbcResult the value for ZYB_GAK.UWBC_RESULT
     *
     * @mbggenerated
     */
    public void setUwbcResult(String uwbcResult) {
        this.uwbcResult = uwbcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.UWBC_UNIT_NAME
     *
     * @return the value of ZYB_GAK.UWBC_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getUwbcUnitName() {
        return uwbcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.UWBC_UNIT_NAME
     *
     * @param uwbcUnitName the value for ZYB_GAK.UWBC_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setUwbcUnitName(String uwbcUnitName) {
        this.uwbcUnitName = uwbcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.UWBC_MINI_RANGE
     *
     * @return the value of ZYB_GAK.UWBC_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getUwbcMiniRange() {
        return uwbcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.UWBC_MINI_RANGE
     *
     * @param uwbcMiniRange the value for ZYB_GAK.UWBC_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setUwbcMiniRange(String uwbcMiniRange) {
        this.uwbcMiniRange = uwbcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.UWBC_MAX_RANGE
     *
     * @return the value of ZYB_GAK.UWBC_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getUwbcMaxRange() {
        return uwbcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.UWBC_MAX_RANGE
     *
     * @param uwbcMaxRange the value for ZYB_GAK.UWBC_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setUwbcMaxRange(String uwbcMaxRange) {
        this.uwbcMaxRange = uwbcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.BLD_RESULT
     *
     * @return the value of ZYB_GAK.BLD_RESULT
     *
     * @mbggenerated
     */
    public String getBldResult() {
        return bldResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.BLD_RESULT
     *
     * @param bldResult the value for ZYB_GAK.BLD_RESULT
     *
     * @mbggenerated
     */
    public void setBldResult(String bldResult) {
        this.bldResult = bldResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.BLD_UNIT_NAME
     *
     * @return the value of ZYB_GAK.BLD_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getBldUnitName() {
        return bldUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.BLD_UNIT_NAME
     *
     * @param bldUnitName the value for ZYB_GAK.BLD_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setBldUnitName(String bldUnitName) {
        this.bldUnitName = bldUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.BLD_MINI_RANGE
     *
     * @return the value of ZYB_GAK.BLD_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getBldMiniRange() {
        return bldMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.BLD_MINI_RANGE
     *
     * @param bldMiniRange the value for ZYB_GAK.BLD_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setBldMiniRange(String bldMiniRange) {
        this.bldMiniRange = bldMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.BLD_MAX_RANGE
     *
     * @return the value of ZYB_GAK.BLD_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getBldMaxRange() {
        return bldMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.BLD_MAX_RANGE
     *
     * @param bldMaxRange the value for ZYB_GAK.BLD_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setBldMaxRange(String bldMaxRange) {
        this.bldMaxRange = bldMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ALT_RESULT
     *
     * @return the value of ZYB_GAK.ALT_RESULT
     *
     * @mbggenerated
     */
    public String getAltResult() {
        return altResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ALT_RESULT
     *
     * @param altResult the value for ZYB_GAK.ALT_RESULT
     *
     * @mbggenerated
     */
    public void setAltResult(String altResult) {
        this.altResult = altResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ALT_UNIT_NAME
     *
     * @return the value of ZYB_GAK.ALT_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getAltUnitName() {
        return altUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ALT_UNIT_NAME
     *
     * @param altUnitName the value for ZYB_GAK.ALT_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setAltUnitName(String altUnitName) {
        this.altUnitName = altUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ALT_MINI_RANGE
     *
     * @return the value of ZYB_GAK.ALT_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getAltMiniRange() {
        return altMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ALT_MINI_RANGE
     *
     * @param altMiniRange the value for ZYB_GAK.ALT_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setAltMiniRange(String altMiniRange) {
        this.altMiniRange = altMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ALT_MAX_RANGE
     *
     * @return the value of ZYB_GAK.ALT_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getAltMaxRange() {
        return altMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ALT_MAX_RANGE
     *
     * @param altMaxRange the value for ZYB_GAK.ALT_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setAltMaxRange(String altMaxRange) {
        this.altMaxRange = altMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ECG_CODE
     *
     * @return the value of ZYB_GAK.ECG_CODE
     *
     * @mbggenerated
     */
    public String getEcgCode() {
        return ecgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ECG_CODE
     *
     * @param ecgCode the value for ZYB_GAK.ECG_CODE
     *
     * @mbggenerated
     */
    public void setEcgCode(String ecgCode) {
        this.ecgCode = ecgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.CHEST_CODE
     *
     * @return the value of ZYB_GAK.CHEST_CODE
     *
     * @mbggenerated
     */
    public String getChestCode() {
        return chestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.CHEST_CODE
     *
     * @param chestCode the value for ZYB_GAK.CHEST_CODE
     *
     * @mbggenerated
     */
    public void setChestCode(String chestCode) {
        this.chestCode = chestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FVC_RESULT
     *
     * @return the value of ZYB_GAK.FVC_RESULT
     *
     * @mbggenerated
     */
    public String getFvcResult() {
        return fvcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FVC_RESULT
     *
     * @param fvcResult the value for ZYB_GAK.FVC_RESULT
     *
     * @mbggenerated
     */
    public void setFvcResult(String fvcResult) {
        this.fvcResult = fvcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FVC_UNIT_NAME
     *
     * @return the value of ZYB_GAK.FVC_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getFvcUnitName() {
        return fvcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FVC_UNIT_NAME
     *
     * @param fvcUnitName the value for ZYB_GAK.FVC_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setFvcUnitName(String fvcUnitName) {
        this.fvcUnitName = fvcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FVC_MINI_RANGE
     *
     * @return the value of ZYB_GAK.FVC_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getFvcMiniRange() {
        return fvcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FVC_MINI_RANGE
     *
     * @param fvcMiniRange the value for ZYB_GAK.FVC_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setFvcMiniRange(String fvcMiniRange) {
        this.fvcMiniRange = fvcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FVC_MAX_RANGE
     *
     * @return the value of ZYB_GAK.FVC_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getFvcMaxRange() {
        return fvcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FVC_MAX_RANGE
     *
     * @param fvcMaxRange the value for ZYB_GAK.FVC_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setFvcMaxRange(String fvcMaxRange) {
        this.fvcMaxRange = fvcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1_RESULT
     *
     * @return the value of ZYB_GAK.FEV1_RESULT
     *
     * @mbggenerated
     */
    public String getFev1Result() {
        return fev1Result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1_RESULT
     *
     * @param fev1Result the value for ZYB_GAK.FEV1_RESULT
     *
     * @mbggenerated
     */
    public void setFev1Result(String fev1Result) {
        this.fev1Result = fev1Result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1_UNIT_NAME
     *
     * @return the value of ZYB_GAK.FEV1_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getFev1UnitName() {
        return fev1UnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1_UNIT_NAME
     *
     * @param fev1UnitName the value for ZYB_GAK.FEV1_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setFev1UnitName(String fev1UnitName) {
        this.fev1UnitName = fev1UnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1_MINI_RANGE
     *
     * @return the value of ZYB_GAK.FEV1_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getFev1MiniRange() {
        return fev1MiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1_MINI_RANGE
     *
     * @param fev1MiniRange the value for ZYB_GAK.FEV1_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setFev1MiniRange(String fev1MiniRange) {
        this.fev1MiniRange = fev1MiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1_MAX_RANGE
     *
     * @return the value of ZYB_GAK.FEV1_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getFev1MaxRange() {
        return fev1MaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1_MAX_RANGE
     *
     * @param fev1MaxRange the value for ZYB_GAK.FEV1_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setFev1MaxRange(String fev1MaxRange) {
        this.fev1MaxRange = fev1MaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1FVC_RESULT
     *
     * @return the value of ZYB_GAK.FEV1FVC_RESULT
     *
     * @mbggenerated
     */
    public String getFev1fvcResult() {
        return fev1fvcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1FVC_RESULT
     *
     * @param fev1fvcResult the value for ZYB_GAK.FEV1FVC_RESULT
     *
     * @mbggenerated
     */
    public void setFev1fvcResult(String fev1fvcResult) {
        this.fev1fvcResult = fev1fvcResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1FVC_UNIT_NAME
     *
     * @return the value of ZYB_GAK.FEV1FVC_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getFev1fvcUnitName() {
        return fev1fvcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1FVC_UNIT_NAME
     *
     * @param fev1fvcUnitName the value for ZYB_GAK.FEV1FVC_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setFev1fvcUnitName(String fev1fvcUnitName) {
        this.fev1fvcUnitName = fev1fvcUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1FVC_MINI_RANGE
     *
     * @return the value of ZYB_GAK.FEV1FVC_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getFev1fvcMiniRange() {
        return fev1fvcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1FVC_MINI_RANGE
     *
     * @param fev1fvcMiniRange the value for ZYB_GAK.FEV1FVC_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setFev1fvcMiniRange(String fev1fvcMiniRange) {
        this.fev1fvcMiniRange = fev1fvcMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.FEV1FVC_MAX_RANGE
     *
     * @return the value of ZYB_GAK.FEV1FVC_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getFev1fvcMaxRange() {
        return fev1fvcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.FEV1FVC_MAX_RANGE
     *
     * @param fev1fvcMaxRange the value for ZYB_GAK.FEV1FVC_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setFev1fvcMaxRange(String fev1fvcMaxRange) {
        this.fev1fvcMaxRange = fev1fvcMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.B_LEAD_RESULT
     *
     * @return the value of ZYB_GAK.B_LEAD_RESULT
     *
     * @mbggenerated
     */
    public String getbLeadResult() {
        return bLeadResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.B_LEAD_RESULT
     *
     * @param bLeadResult the value for ZYB_GAK.B_LEAD_RESULT
     *
     * @mbggenerated
     */
    public void setbLeadResult(String bLeadResult) {
        this.bLeadResult = bLeadResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.B_LEAD_UNIT_NAME
     *
     * @return the value of ZYB_GAK.B_LEAD_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getbLeadUnitName() {
        return bLeadUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.B_LEAD_UNIT_NAME
     *
     * @param bLeadUnitName the value for ZYB_GAK.B_LEAD_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setbLeadUnitName(String bLeadUnitName) {
        this.bLeadUnitName = bLeadUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.B_LEAD_MINI_RANGE
     *
     * @return the value of ZYB_GAK.B_LEAD_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getbLeadMiniRange() {
        return bLeadMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.B_LEAD_MINI_RANGE
     *
     * @param bLeadMiniRange the value for ZYB_GAK.B_LEAD_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setbLeadMiniRange(String bLeadMiniRange) {
        this.bLeadMiniRange = bLeadMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.B_LEAD_MAX_RANGE
     *
     * @return the value of ZYB_GAK.B_LEAD_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getbLeadMaxRange() {
        return bLeadMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.B_LEAD_MAX_RANGE
     *
     * @param bLeadMaxRange the value for ZYB_GAK.B_LEAD_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setbLeadMaxRange(String bLeadMaxRange) {
        this.bLeadMaxRange = bLeadMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.U_LEAD_RESULT
     *
     * @return the value of ZYB_GAK.U_LEAD_RESULT
     *
     * @mbggenerated
     */
    public String getuLeadResult() {
        return uLeadResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.U_LEAD_RESULT
     *
     * @param uLeadResult the value for ZYB_GAK.U_LEAD_RESULT
     *
     * @mbggenerated
     */
    public void setuLeadResult(String uLeadResult) {
        this.uLeadResult = uLeadResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.U_LEAD_UNIT_NAME
     *
     * @return the value of ZYB_GAK.U_LEAD_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getuLeadUnitName() {
        return uLeadUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.U_LEAD_UNIT_NAME
     *
     * @param uLeadUnitName the value for ZYB_GAK.U_LEAD_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setuLeadUnitName(String uLeadUnitName) {
        this.uLeadUnitName = uLeadUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.U_LEAD_MINI_RANGE
     *
     * @return the value of ZYB_GAK.U_LEAD_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getuLeadMiniRange() {
        return uLeadMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.U_LEAD_MINI_RANGE
     *
     * @param uLeadMiniRange the value for ZYB_GAK.U_LEAD_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setuLeadMiniRange(String uLeadMiniRange) {
        this.uLeadMiniRange = uLeadMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.U_LEAD_MAX_RANGE
     *
     * @return the value of ZYB_GAK.U_LEAD_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getuLeadMaxRange() {
        return uLeadMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.U_LEAD_MAX_RANGE
     *
     * @param uLeadMaxRange the value for ZYB_GAK.U_LEAD_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setuLeadMaxRange(String uLeadMaxRange) {
        this.uLeadMaxRange = uLeadMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ZPP_RESULT
     *
     * @return the value of ZYB_GAK.ZPP_RESULT
     *
     * @mbggenerated
     */
    public String getZppResult() {
        return zppResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ZPP_RESULT
     *
     * @param zppResult the value for ZYB_GAK.ZPP_RESULT
     *
     * @mbggenerated
     */
    public void setZppResult(String zppResult) {
        this.zppResult = zppResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ZPP_UNIT_NAME
     *
     * @return the value of ZYB_GAK.ZPP_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getZppUnitName() {
        return zppUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ZPP_UNIT_NAME
     *
     * @param zppUnitName the value for ZYB_GAK.ZPP_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setZppUnitName(String zppUnitName) {
        this.zppUnitName = zppUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ZPP_MINI_RANGE
     *
     * @return the value of ZYB_GAK.ZPP_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getZppMiniRange() {
        return zppMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ZPP_MINI_RANGE
     *
     * @param zppMiniRange the value for ZYB_GAK.ZPP_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setZppMiniRange(String zppMiniRange) {
        this.zppMiniRange = zppMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.ZPP_MAX_RANGE
     *
     * @return the value of ZYB_GAK.ZPP_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getZppMaxRange() {
        return zppMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.ZPP_MAX_RANGE
     *
     * @param zppMaxRange the value for ZYB_GAK.ZPP_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setZppMaxRange(String zppMaxRange) {
        this.zppMaxRange = zppMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.NEUT_RESULT
     *
     * @return the value of ZYB_GAK.NEUT_RESULT
     *
     * @mbggenerated
     */
    public String getNeutResult() {
        return neutResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.NEUT_RESULT
     *
     * @param neutResult the value for ZYB_GAK.NEUT_RESULT
     *
     * @mbggenerated
     */
    public void setNeutResult(String neutResult) {
        this.neutResult = neutResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.NEUT_UNIT_NAME
     *
     * @return the value of ZYB_GAK.NEUT_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getNeutUnitName() {
        return neutUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.NEUT_UNIT_NAME
     *
     * @param neutUnitName the value for ZYB_GAK.NEUT_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setNeutUnitName(String neutUnitName) {
        this.neutUnitName = neutUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.NEUT_MINI_RANGE
     *
     * @return the value of ZYB_GAK.NEUT_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getNeutMiniRange() {
        return neutMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.NEUT_MINI_RANGE
     *
     * @param neutMiniRange the value for ZYB_GAK.NEUT_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setNeutMiniRange(String neutMiniRange) {
        this.neutMiniRange = neutMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.NEUT_MAX_RANGE
     *
     * @return the value of ZYB_GAK.NEUT_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getNeutMaxRange() {
        return neutMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.NEUT_MAX_RANGE
     *
     * @param neutMaxRange the value for ZYB_GAK.NEUT_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setNeutMaxRange(String neutMaxRange) {
        this.neutMaxRange = neutMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HEARING_REUSLT
     *
     * @return the value of ZYB_GAK.HEARING_REUSLT
     *
     * @mbggenerated
     */
    public String getHearingReuslt() {
        return hearingReuslt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HEARING_REUSLT
     *
     * @param hearingReuslt the value for ZYB_GAK.HEARING_REUSLT
     *
     * @mbggenerated
     */
    public void setHearingReuslt(String hearingReuslt) {
        this.hearingReuslt = hearingReuslt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HEARING_UNIT_NAME
     *
     * @return the value of ZYB_GAK.HEARING_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getHearingUnitName() {
        return hearingUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HEARING_UNIT_NAME
     *
     * @param hearingUnitName the value for ZYB_GAK.HEARING_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setHearingUnitName(String hearingUnitName) {
        this.hearingUnitName = hearingUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HEARING_MINI_RANGE
     *
     * @return the value of ZYB_GAK.HEARING_MINI_RANGE
     *
     * @mbggenerated
     */
    public String getHearingMiniRange() {
        return hearingMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HEARING_MINI_RANGE
     *
     * @param hearingMiniRange the value for ZYB_GAK.HEARING_MINI_RANGE
     *
     * @mbggenerated
     */
    public void setHearingMiniRange(String hearingMiniRange) {
        this.hearingMiniRange = hearingMiniRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.HEARING_MAX_RANGE
     *
     * @return the value of ZYB_GAK.HEARING_MAX_RANGE
     *
     * @mbggenerated
     */
    public String getHearingMaxRange() {
        return hearingMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.HEARING_MAX_RANGE
     *
     * @param hearingMaxRange the value for ZYB_GAK.HEARING_MAX_RANGE
     *
     * @mbggenerated
     */
    public void setHearingMaxRange(String hearingMaxRange) {
        this.hearingMaxRange = hearingMaxRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.RPBT_CODE
     *
     * @return the value of ZYB_GAK.RPBT_CODE
     *
     * @mbggenerated
     */
    public Short getRpbtCode() {
        return rpbtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.RPBT_CODE
     *
     * @param rpbtCode the value for ZYB_GAK.RPBT_CODE
     *
     * @mbggenerated
     */
    public void setRpbtCode(Short rpbtCode) {
        this.rpbtCode = rpbtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.WRIGHT_CODE
     *
     * @return the value of ZYB_GAK.WRIGHT_CODE
     *
     * @mbggenerated
     */
    public BigDecimal getWrightCode() {
        return wrightCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.WRIGHT_CODE
     *
     * @param wrightCode the value for ZYB_GAK.WRIGHT_CODE
     *
     * @mbggenerated
     */
    public void setWrightCode(BigDecimal wrightCode) {
        this.wrightCode = wrightCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.CONCLUSIONS_CODE
     *
     * @return the value of ZYB_GAK.CONCLUSIONS_CODE
     *
     * @mbggenerated
     */
    public Short getConclusionsCode() {
        return conclusionsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.CONCLUSIONS_CODE
     *
     * @param conclusionsCode the value for ZYB_GAK.CONCLUSIONS_CODE
     *
     * @mbggenerated
     */
    public void setConclusionsCode(Short conclusionsCode) {
        this.conclusionsCode = conclusionsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SHBZ
     *
     * @return the value of ZYB_GAK.SHBZ
     *
     * @mbggenerated
     */
    public String getShbz() {
        return shbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SHBZ
     *
     * @param shbz the value for ZYB_GAK.SHBZ
     *
     * @mbggenerated
     */
    public void setShbz(String shbz) {
        this.shbz = shbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SHSJ
     *
     * @return the value of ZYB_GAK.SHSJ
     *
     * @mbggenerated
     */
    public Date getShsj() {
        return shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SHSJ
     *
     * @param shsj the value for ZYB_GAK.SHSJ
     *
     * @mbggenerated
     */
    public void setShsj(Date shsj) {
        this.shsj = shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SBBZ
     *
     * @return the value of ZYB_GAK.SBBZ
     *
     * @mbggenerated
     */
    public String getSbbz() {
        return sbbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SBBZ
     *
     * @param sbbz the value for ZYB_GAK.SBBZ
     *
     * @mbggenerated
     */
    public void setSbbz(String sbbz) {
        this.sbbz = sbbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SBYY
     *
     * @return the value of ZYB_GAK.SBYY
     *
     * @mbggenerated
     */
    public String getSbyy() {
        return sbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SBYY
     *
     * @param sbyy the value for ZYB_GAK.SBYY
     *
     * @mbggenerated
     */
    public void setSbyy(String sbyy) {
        this.sbyy = sbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.SBSJ
     *
     * @return the value of ZYB_GAK.SBSJ
     *
     * @mbggenerated
     */
    public Date getSbsj() {
        return sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.SBSJ
     *
     * @param sbsj the value for ZYB_GAK.SBSJ
     *
     * @mbggenerated
     */
    public void setSbsj(Date sbsj) {
        this.sbsj = sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZYB_GAK.LOGSJ
     *
     * @return the value of ZYB_GAK.LOGSJ
     *
     * @mbggenerated
     */
    public Date getLogsj() {
        return logsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZYB_GAK.LOGSJ
     *
     * @param logsj the value for ZYB_GAK.LOGSJ
     *
     * @mbggenerated
     */
    public void setLogsj(Date logsj) {
        this.logsj = logsj;
    }

    public Date getBodyCheckTime() {
        return bodyCheckTime;
    }

    public void setBodyCheckTime(Date bodyCheckTime) {
        this.bodyCheckTime = bodyCheckTime;
    }
}